version: '3.11'
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: cocktail_container
    command: python3 manage.py runserver 0.0.0.0:8000